### ISSUE TITLE
USB ACM device is not recognised in overo

### ISSUE THREAD

**Issue by ymkim92** [gumstix/linux#4]
I am running new kernel of 3.17.8 in overo:

    root@overo:~# uname -a
    Linux overo 3.17.8-custom #1 SMP Fri Mar 27 20:51:48 AEST 2015 armv7l GNU/Linux

I cannot find cdc_acm module using lsmod and 'modprobe cdc_acm' did not work.
This is the output as I push it to the USB port.

    modprobe cdc[ 2243.645111] usb 1-2.4: new full-speed USB device number 6 using ehci-omap
    [ 2243.777465] usb 1-2.4: New USB device found, idVendor=2341, idProduct=0010
    [ 2243.784942] usb 1-2.4: New USB device strings: Mfr=1, Product=2, SerialNumber=220
    [ 2243.792968] usb 1-2.4: Product: Arduino Mega 2560
    [ 2243.798065] usb 1-2.4: Manufacturer: Arduino (www.arduino.cc)
    [ 2243.804199] usb 1-2.4: SerialNumber: A4830363438351314041

There should be one more line like this:

    [   30.175445] cdc_acm 1-2.4:1.0: ttyACM3: USB ACM device

**Comment by ymkim92** [comment]
After I add cdc_acm module into Kernel as "M", it is working!
Using this command:

    bitbake -c menuconfig virtual/kernel

**Comment by ashcharles** [comment]
I pushed the corresponding change to the meta-gumstix branch. https://github.com/gumstix/meta-gumstix/commit/ba1ddd002c45054d1890d379c41a1cc9f0b17be7
