### ISSUE TITLE
Is there any plans to androidize this kernel?

### ISSUE THREAD

**Issue by chavhector** [gumstix/linux#5]
I have a gumstix multitouch appliance kit which I have the need to run Android on it...
Is there any plans to androidize this kernel?
I already completed my development with Yocto/Poky, the next step is to enable the same harware for Android.

Thanks.

**Comment by yangjiel** [comment]
Hello there, we have android 4.3 for pepper-43c board. Please see [gumdroid](https://github.com/gumdroid).
