### ISSUE TITLE
USB host instability

### ISSUE THREAD

**Issue by berniwa** [gumstix/linux#6]
The kernel, that ships with the gumstix modules is still susceptible to the "disabled by hub (EMI?)" issue on the USB port.

Our application is heavily dependent on a working USB connection, but due to the issues described in TI Errata SPRZ319 - Advisory 2.1 the USB communication fails after several weeks of operation.

The attached patch is a very crude fix, that should set the PLL values according to TI's suggestions.

[SPRZ319-2.1-USB-instability.txt](https://github.com/gumstix/linux/files/346375/SPRZ319-2.1-USB-instability.txt)

**Comment by yangjiel** [comment]
I am now maintaining the gumstix kernel. Could you specify which branch is it? Thank you.

**Comment by yangjiel** [comment]
Close for no responding for now. I recommend you to make a pull request to contribute your patch and gain credit.
